apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: document_search
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis:6379
